### ISSUE TITLE
Файл должен называться .gitignore

### ISSUE THREAD

**Issue by coursar** [PomaPoma282/Sportmaster#3]

**Comment by PomaPoma282** [comment]
Пытаюсь заново добавить .gitignore и залить его на репозиторий, а идея отвечает "Push to origin/master was rejected"

**Comment by coursar** [comment]
Скриншот пришлите или ошибку целиком.

**Comment by PomaPoma282** [comment]
![image](https://user-images.githubusercontent.com/45179207/49248707-68927580-f42b-11e8-83ee-a4b8fa044dde.png)

**Comment by coursar** [comment]
@PomaPoma282, Alt + 9 вкладка Console. Пришлите скриншот.

**Comment by PomaPoma282** [comment]
![image](https://user-images.githubusercontent.com/45179207/49305418-49095480-f4e0-11e8-9f1d-652007eba987.png)

**Comment by coursar** [comment]
Наверху справа есть кнопка update project

**Comment by PomaPoma282** [comment]
![image](https://user-images.githubusercontent.com/45179207/49305557-9ab1df00-f4e0-11e8-8604-95a6da0242ce.png)

**Comment by PomaPoma282** [comment]
Ее уже нажимал - вот такая ошибка

**Comment by PomaPoma282** [comment]
![image](https://user-images.githubusercontent.com/45179207/49305578-b0270900-f4e0-11e8-8f30-2ba99e3d8556.png)

**Comment by PomaPoma282** [comment]
Так, .gitignore смог добавить только с ноута, с компа все такая же ошибка.
Ну ладно, вопрос другой. Почему у меня никак не реагирует Ctrl + Alt + A , чтоб "активировать" gitignore?

**Comment by PomaPoma282** [comment]
@coursar сделано
